# Generated by Django 6.0.6 on 2026-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food')], default='Grammar', max_length=100),
            preserve_default=False,
        ),
    ]
