# Generated by Django 6.0.6 on 2026-07-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('web', '0002_trialbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbooking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_bookings', to='schedules.classsession'),
        ),
        migrations.AlterField(
            model_name='trialbooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trialbooking',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
